version: '3.8'

services:
  web:
    image: placeholder:latest  # Se actualizará automáticamente en el despliegue
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production